# Generated by Django 4.1.7 on 2023-02-20 06:17

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_rename_status_taskdetail_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetail",
            name="assigned_time",
            field=models.DateField(default=task.models.TaskDetail.assigned),
        ),
    ]
