# Generated by Django 4.1.7 on 2023-02-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_taskdetail_assigned_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskdetail",
            old_name="completed",
            new_name="is_task_completed",
        ),
    ]
