# Generated by Django 4.1.7 on 2023-02-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_rename_completed_taskdetail_is_task_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetail",
            name="assigned_time",
            field=models.DateTimeField(),
        ),
    ]
