# Generated by Django 4.1.7 on 2023-02-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0007_alter_taskdetail_assigned_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="taskdetail",
            old_name="assigned_time",
            new_name="estimated_time",
        ),
        migrations.RemoveField(
            model_name="taskdetail",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="taskdetail",
            name="id",
        ),
        migrations.AddField(
            model_name="taskdetail",
            name="basemodel_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="task.basemodel",
            ),
            preserve_default=False,
        ),
    ]
